### ISSUE TITLE
Syntax Discussion

### ISSUE THREAD

**Issue by bjskistad** [jel-lang/jel#10]
This is the place to discuss general syntax. Including but not limited to:
Syntax Errors
Syntax Improvements
Syntax Suggestions
Etc.

Current function syntax:

    jel(arg1, arg2,) {
        code...
    };
Current if statement syntax:

    if(condition) {
        code...
    }

**Comment by CosmicWebServices** [comment]
You should add the CURRENT syntax Ideas here!

**Comment by bjskistad** [comment]
M'kay.

**Comment by bjskistad** [comment]
Like what?

**Comment by bjskistad** [comment]
I'll add function syntax, if statement syntax, and variable syntax.

**Comment by CosmicWebServices** [comment]
OK

**Comment by 109C** [comment]
Is there a place where all of the language syntax is defined?

**Comment by CosmicWebServices** [comment]
Yes look at first comment I am thinking more will be added soon. Are Variables `var x=1;`?

**Comment by bjskistad** [comment]
Variables will be like variables in Python. `x = 1;`

**Comment by CosmicWebServices** [comment]
`import Lib;`

Is this a thing?

**Comment by bjskistad** [comment]
Hmm... I guess so. But it will be `import(Lib)`

**Comment by CosmicWebServices** [comment]
OK

**Comment by bjskistad** [comment]
We need to have a package manager then...

**Comment by CosmicWebServices** [comment]
What work would it take.

**Comment by bjskistad** [comment]
Lemme research modules...

**Comment by 109C** [comment]
@bjskistad We should probably get the grammar done before implementing other stuff.

**Comment by bjskistad** [comment]
Yeah.

**Comment by bjskistad** [comment]
We're trashing semi-colons and parentheses. (YASSSS!!!) We're gonna be like Python.

**Comment by CosmicWebServices** [comment]
Realy?

**Comment by CosmicWebServices** [comment]
Then what is the point...

**Comment by bjskistad** [comment]
To have functions without parentheses... I was teaching a coding class to 15 kids and they asked me, "What's the point of having parentheses if you have the quotes?". Then it made total sense, make a language with the parentheses, as they are extra chars.

**Comment by CosmicWebServices** [comment]
True

**Comment by bjskistad** [comment]
:)

**Comment by Omegabyte** [comment]
So does it still use semi-colons??? If so... Update README

**Comment by bjskistad** [comment]
Yeah. XD

**Comment by Omegabyte** [comment]
Maybe we shouldn't use parentheses (comparison):
`write 'hello'`
`write('hello')`

**Comment by bjskistad** [comment]
ok... y not?

**Comment by Omegabyte** [comment]
It's more readable and easier to write.

**Comment by bjskistad** [comment]
See #14.

**Comment by Jonathan50** [comment]
> We need to have a package manager then...

you at minimum only need a basic module system

**Comment by bjskistad** [comment]
@Jonathan50 And that would be....

**Comment by bjskistad** [comment]
@Jonathan50 ^

**Comment by Jonathan50** [comment]
What do you mean?

**Comment by bjskistad** [comment]
What's the basic module system? You're an ATer, not me. XD

**Comment by Jonathan50** [comment]
I said *a* basic module system. https://en.wikipedia.org/wiki/Modular_programming

**Comment by bjskistad** [comment]
Is there something I can reference to? A repo? Wiki page? Something that gives basic source code?

**Comment by Jonathan50** [comment]
> Is there something I can reference to? A repo? Wiki page? Something that gives basic source code?

?

**Comment by Jonathan50** [comment]
Again, there is no "the" module system.

**Comment by bjskistad** [comment]
Is there something I can base it off of?
