### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by herohamp** [jel-lang/jel#13]
http://prntscr.com/b3099l

**Comment by herohamp** [comment]
herohamp:Downloads hamptonmoore$ sudo mv jel/jel /bin
mv: rename jel/jel to /bin/jel: Operation not permitted

**Comment by bjskistad** [comment]
Hmmm... That might only work for Cloud9

**Comment by herohamp** [comment]
hmm

**Comment by herohamp** [comment]
I also typed
python jel.py /examples/count_to.jel 

and nothing happened

**Comment by herohamp** [comment]
NVM I installed. Should I upload how?

**Comment by bjskistad** [comment]
Yeah. What editor are you using? Btw the reason nothing happened when you did `python jel.py /examples/count-to.jel` is because the parser isn't parsing yet. XD

**Comment by bjskistad** [comment]
That means yeah, tell me.

**Comment by bjskistad** [comment]
Are you able to run `jel` commands now.

**Comment by bjskistad** [comment]
I'm going to close it but be sure to tell me how. :)

**Comment by herohamp** [comment]
I use my mac as an editor ;P

**Comment by herohamp** [comment]
to install on mac do
sudo mv jel/jel /bin/local/

**Comment by bjskistad** [comment]
I edited the RM.

**Comment by bjskistad** [comment]
We need to figure out if that's the same for Windows or if it is only for Mac. Either way worked for me in my C9 editor.

**Comment by herohamp** [comment]
yeah because C9 is system that does not care about being corrupted! it lets you do ANYTHING! But on macs the system does not what you to break your system! :P

**Comment by bjskistad** [comment]
Ok.... XD Could you try it on Windows?

**Comment by herohamp** [comment]
I don't have stupid Windows 😜

**Comment by bjskistad** [comment]
K.

**Comment by bjskistad** [comment]
Do you know anybody who uses Windows?

**Comment by herohamp** [comment]
Yup

**Comment by bjskistad** [comment]
Could you have them try it out?

**Comment by herohamp** [comment]
I will see

**Comment by bjskistad** [comment]
K thanks!

**Comment by bjskistad** [comment]
@herohamp Can you run jel with the `jel.run` file? It works for my C9IDE.

**Comment by Omegabyte** [comment]
I'll try it on Code Anywhere IDE once I get the time.

**Comment by bjskistad** [comment]
K.
