### ISSUE TITLE
Ambiguity

### ISSUE THREAD

**Issue by BookOwl** [jel-lang/jel#14]
I hate to break it to you guys, but if you allow user-defined callables, your language will became ambiguous.
```
var = list foo 1 bar x 5 + 7
```
How would you parse this?

**Comment by BookOwl** [comment]
It could be
```
list(foo(1), bar, x, 5 + 7)
# or
list(foo, 1, bar(x, 5)+7)
# or
list(foo(1, bar(x, 5+7)))
```
Without parens, you can't tell

**Comment by BookOwl** [comment]
Actually, if you allow first class functions, just using builtins would be ambiguous.

**Comment by bjskistad** [comment]
For lists we would use `[]` not parens.

**Comment by bjskistad** [comment]
What do you mean by 'first class functions'?

**Comment by bjskistad** [comment]
btw there would still be commas.

**Comment by BookOwl** [comment]
The point is that you can't tell the meaning of an expression without parens if you use infix syntax

**Comment by BookOwl** [comment]
first class functions mean that you can pass functions around and put them in lists and stuff

**Comment by BookOwl** [comment]
commas wouldn't help

**Comment by bjskistad** [comment]
So

    var = list foo 1 bar x 5 + 7

would actually be

    var - list foo 1, bar, x, 5 + 7

**Comment by BookOwl** [comment]
if the assignment is `-`, how are you going to represent subtraction?

**Comment by bjskistad** [comment]
And for first class functions we would do this:

    myFunct arg1, arg2 {
        return arg1
        return arg2
    }
    
    myList = myFunct "My String"\, "My Second String", 1
    write myList

**Comment by bjskistad** [comment]
@BookOwl Typo, sorry. XD :P

**Comment by bjskistad** [comment]
Btw that would write

    My String
    My Second String
    1

**Comment by BookOwl** [comment]
`x a b c, d, e f g` is ambiguous. Does it mean `x(a(b(c)), d, e(f(g)))` or `x(a)(b)(c, d, e(f(g)))`

**Comment by bjskistad** [comment]
I explained that before, function args are separated with backslashes.

    x a\, b\, c\, d e\, f\, g

**Comment by BookOwl** [comment]
I thought you said that they were separated with commas...

**Comment by bjskistad** [comment]
They are. GAHH. It will interpret anything after x that has a backslash before the comma as an argument.

**Comment by bjskistad** [comment]
This is gonna be an issue. I can tell.

**Comment by bjskistad** [comment]
If we called a function as an argument of a function, it wouldn't be possible.

**Comment by bjskistad** [comment]
What do you suggest?

**Comment by BookOwl** [comment]
`a b c d` is ambiguous. It could be any of
```
a(b(c(d)))
// or
a(b)(c)(d)
// or
a(b(c))(d)
```
a,b,c,d are all one argument functions returning a function

**Comment by bjskistad** [comment]
What do you suggest?

**Comment by bjskistad** [comment]
Using parens?

**Comment by BookOwl** [comment]
I would make using parens optional and using a standard order if they are not used. If the programmer wants a different order, he can add them.
This is pretty much how math expressions work.

**Comment by bjskistad** [comment]
K

**Comment by BookOwl** [comment]
for example, `a b c d` would mean `a(b(c(d)))`, but if they used they could change it to `(a b) c d`, which would mean `a(b)(c(d)`

**Comment by BookOwl** [comment]
That should fix this, so I'll close this issue

**Comment by bjskistad** [comment]
What do you think about colons and semi-colons?

**Comment by bjskistad** [comment]
It could be `a:b, c, d;`. The colons representing the start and end.

**Comment by Jonathan50** [comment]
> Actually, if you allow first class functions, just using builtins would be ambiguous.

Not if all procedures only accept one argument like in Haskell and ML.
