### ISSUE TITLE
What differentiates Jel from Python?

### ISSUE THREAD

**Issue by Omegabyte** [jel-lang/jel#15]
`I know this should go in syntax discussion but this is really important.`
I mean besides different syntax for functions, nothing major.
We need to add unique things that will make Jel special.

**Comment by Omegabyte** [comment]
Also the write command doesn't work and I'm guessing there's no semicolons.

**Comment by bjskistad** [comment]
No semi-colons, but yes,MIT does have the newline character (`\n`) built in. It's basically JavaScript with Python syntax. I think we're switching over to client side, we'll be using JavaScript for that. If we want to add backend too, we could maybe program some in Python.

**Comment by Omegabyte** [comment]
Cool, so it's like JavaScript but more readable.
The parser doesn't do anything, it's just says hi.

**Comment by Omegabyte** [comment]
We should first develop server-side then make a client side version.

**Comment by Omegabyte** [comment]
> No semi-colons, but yes, it does have the newline character (\n) built in. It's basically JavaScript with Python syntax. I think we're switching over to client side, we'll be using JavaScript or Brython for that. If we want to add backend too, we could maybe program some in Python.
So what is the point of Jel? Brython is client side python, what makes Jel different?

**Comment by bjskistad** [comment]
It's basically unfancy-backend, JS made for kids.

**Comment by bjskistad** [comment]
Something's wrong with the JS file.

    Traceback (most recent call last):
  File "/bin/jel", line 95, in <module>
    exec(js)
  File "jel.js", line 1
    var hi = 'sup';
         ^
    SyntaxError: invalid syntax

**Comment by bjskistad** [comment]
Oh lol. It's executing Python on a JS file. XD
