### ISSUE TITLE
Versions 2.0.5 through 2.1.0 missing lib/jel.js

### ISSUE THREAD

**Issue by iarna** [jel-lang/jel#17]
Versions 2.0.5 to 2.1.0 as published on the npm registry seem to be missing `lib/jel.js`.

It's quite possible you're being burned by https://github.com/npm/npm/issues/5082 – unfortunately until that's fixed, all I can recommend is trying your publishes from a different machine maybe? It's a race condition, so different performance characteristics can make it go away. Other than that, you'll unfortunately need to test your published packages to be sure they're ok.

The error your users will get with the packages missing `lib/jel.js` is the unfortunately entirely opaque:

```
5113 error path /working/directory/node_modules/jel/lib/jel.js
5114 error code ENOENT
5115 error errno -2
5116 error syscall chmod
5117 error enoent ENOENT: no such file or directory, chmod '/working/directory/node_modules/jel/lib/jel.js'
5117 error enoent This is most likely not a problem with npm itself
5117 error enoent and is related to npm not being able to find a file.
```

**Comment by bjskistad** [comment]
@iarna Would unpublishing versions fix the problem?

**Comment by iarna** [comment]
yup, that's probably a good thing to do as well

**Comment by bjskistad** [comment]
Fixed it by getting rid of `lib/jel.js` and renaming it to `jel.js`. Works now. Thanks for your help! :D
