### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by herohamp** [jel-lang/jel#2]
How do I run jel

**Comment by bjskistad** [comment]
1) Jel isn't actually running anything yet. 2) 1st, download using `npm install jel`. Then, try running `./jel.py -help` both in your terminal, if it doesn't work, you'll have to run some other things.

**Comment by bjskistad** [comment]
You need to clarify what you want to run.

**Comment by herohamp** [comment]
run a .jel file

**Comment by bjskistad** [comment]
Did you do step 2?

**Comment by bjskistad** [comment]
Hellooooo?

**Comment by CosmicWebServices** [comment]
I think we should close this... I mean maybe it is too complex to run.

**Comment by bjskistad** [comment]
What do you mean to complex?  
The parser simply isn't ready to actually run anything yet. XD It isn't parsing commands and executing them.

**Comment by CosmicWebServices** [comment]
never mind I think we should just close it

**Comment by bjskistad** [comment]
I know what's going on. I got this. ;)

**Comment by CosmicWebServices** [comment]
OK

**Comment by herohamp** [comment]
Yes I did

**Comment by bjskistad** [comment]
K. :D
