### ISSUE TITLE
FFI

### ISSUE THREAD

**Issue by bjskistad** [jel-lang/jel#3]
We're going to need to add some FFIs

**Comment by CosmicWebServices** [comment]
What is FFI?

**Comment by bjskistad** [comment]
Foreign Function Interface. See https://en.wikipedia.org/wiki/Foreign_function_interface

**Comment by CosmicWebServices** [comment]
OK so I will see what I can do...

**Comment by bjskistad** [comment]
KK.

**Comment by bjskistad** [comment]
@CosmicWebServices Maybe instead we should make a setup.py file?

**Comment by bjskistad** [comment]
For right now.

**Comment by CosmicWebServices** [comment]
that make sense. Just so I won't mess up what exactly do you want the setup.py to do.

**Comment by bjskistad** [comment]
Run the `chmod +x jel.py` script so that jel.py is executable for now.

**Comment by CosmicWebServices** [comment]
I made _init_.py I just do not understand what `chmod +x jel.py` means

**Comment by bjskistad** [comment]
Well first, what does a setup.py file do?

**Comment by CosmicWebServices** [comment]
This https://docs.python.org/2/distutils/setupscript.html

**Comment by CosmicWebServices** [comment]
Wait so we are using Python 3

**Comment by CosmicWebServices** [comment]
so then this https://docs.python.org/3.5/distutils/setupscript.html

**Comment by bjskistad** [comment]
Oh, I see.

**Comment by bjskistad** [comment]
Hmmm...

**Comment by bjskistad** [comment]
Nvm the `chmod +x`

**Comment by CosmicWebServices** [comment]
I made a pull request

**Comment by bjskistad** [comment]
Merged #6

**Comment by CosmicWebServices** [comment]
OK Thanks!

**Comment by CosmicWebServices** [comment]
What to do next?

**Comment by bjskistad** [comment]
We need to find a way to successfully import files as modules in the code directory.

**Comment by CosmicWebServices** [comment]
What do you mean by successful have you tried?

**Comment by bjskistad** [comment]
#7 Let's start talking there.

**Comment by CosmicWebServices** [comment]
OK
