### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by bjskistad** [jel-lang/jel#7]
Please refer to here to discuss what to do next, general discussion, etc.

**Comment by CosmicWebServices** [comment]
So have you tried this before? And if so where is it?

**Comment by bjskistad** [comment]
Yes.

**Comment by bjskistad** [comment]
I tried to import this whole directory https://github.com/jel-lang/jel/tree/master/code in jel.py

**Comment by CosmicWebServices** [comment]
Where is the code maybe I could attempt to fix it

**Comment by bjskistad** [comment]
https://github.com/jel-lang/jel/blob/master/jel.py

**Comment by CosmicWebServices** [comment]
OK

**Comment by bjskistad** [comment]
Wait.

**Comment by bjskistad** [comment]
Wait.

**Comment by bjskistad** [comment]
I've got to put it back in there. I had a merge conflict and had to reverse it.

**Comment by CosmicWebServices** [comment]
Oh OK

**Comment by bjskistad** [comment]
K. Should be there now.

**Comment by bjskistad** [comment]
Yep it is.

**Comment by CosmicWebServices** [comment]
OK

**Comment by bjskistad** [comment]
So now the problem, I believe it thinks I'm trying to import the `code` module, but I'm not, but it always checks for modules before files and directories.

**Comment by CosmicWebServices** [comment]
Yep I was just going to say that.

**Comment by CosmicWebServices** [comment]
We should add [Travis.ci](https://github.com/integrations/travis-ci).

**Comment by bjskistad** [comment]
lol ok

**Comment by CosmicWebServices** [comment]
It may help

**Comment by bjskistad** [comment]
K. Added it to the org... We need to add a `.travis.yml` file.

**Comment by CosmicWebServices** [comment]
I can do it

**Comment by bjskistad** [comment]
Added travis to the repo.

**Comment by CosmicWebServices** [comment]
OK

**Comment by bjskistad** [comment]
Make a PR?

**Comment by CosmicWebServices** [comment]
`.travis.yml` file

**Comment by CosmicWebServices** [comment]
Wait I think u have to do it. https://docs.travis-ci.com/user/languages/python

**Comment by bjskistad** [comment]
k

**Comment by bjskistad** [comment]
Just enabled it...

**Comment by CosmicWebServices** [comment]
OK I got to go!

**Comment by bjskistad** [comment]
K! See ya later today?

**Comment by CosmicWebServices** [comment]
Maybe...

**Comment by bjskistad** [comment]
K. :)

**Comment by bjskistad** [comment]
Hello?

**Comment by bjskistad** [comment]
It's working!

**Comment by CosmicWebServices** [comment]
What is?

**Comment by bjskistad** [comment]
Travis CI

**Comment by CosmicWebServices** [comment]
Cool!

**Comment by bjskistad** [comment]
:D

**Comment by Omegabyte** [comment]
What is Jel targeted for? Does it run client side like javascript or server side like python?

**Comment by bjskistad** [comment]
As of now, server side scripting.

**Comment by bjskistad** [comment]
Still trying to figure out basic syntax. We're having some issues. #14

**Comment by Omegabyte** [comment]
Does jel support python modules or javascript libraries? Or both?

**Comment by bjskistad** [comment]
A few python modules.

**Comment by bjskistad** [comment]
I'm thinking we should switch over to client side.

**Comment by bjskistad** [comment]
As of now, JS is the only language that supports client side.

**Comment by Omegabyte** [comment]
You could try running jel on brython (http://brython.info) or convert with pyjs (http://pyjs.org).

**Comment by Omegabyte** [comment]
brython would allow support of JS libraries.

**Comment by bjskistad** [comment]
K.

**Comment by bjskistad** [comment]
Should probably use that. XD

**Comment by bjskistad** [comment]
Should we switch to JS for the interpreter?

**Comment by bjskistad** [comment]
We'll use PY for the terminal commands.

**Comment by Omegabyte** [comment]
Use JS for an interpreter??? *facepalm* Then there's no server-side support.

**Comment by Omegabyte** [comment]
I'm too lazy too rewrite the interpreter, just use brython, It has modules for using JS and DOM.

**Comment by CosmicWebServices** [comment]
OK

**Comment by bjskistad** [comment]
Hey guys! I just released Jel Doctor, feel free to check out the release for more!

**Comment by CosmicWebServices** [comment]
OK

**Comment by Jonathan50** [comment]
Or compile to JavaScript.
